### PR TITLE
Fixes operations with parameters included in single quotes

### PR DESCRIPTION
**Pull request by salemXpresso**
Example:
@Given("Given a symbol '$symbol'")
Should be matched by :
Given a symbol '555'

### CODE REVIEW

**Comment by marcelobusico** [comment]
Thank you so much! @salemXpresso Do you need a new version published in netbeans plugin center? Thanks again! Marcelo.

**Comment by salemXpresso** [comment]
Thanks for your quick response. A new version would be great if it's not too much to ask !

**Comment by marcelobusico** [comment]
@salemXpresso I have created the new release and published at:
https://github.com/marcelobusico/jbehave-netbeans-plugin/releases/tag/v4.2.2

You can download this new NBM from:
https://github.com/marcelobusico/jbehave-netbeans-plugin/releases/download/v4.2.2/jbehave-plugin-v4.2.2.nbm

I will request and update in Netbeans plugin center but that may take some time to be approved. Thanks a lot for your contribution. Please let me know if this new version is working as expected.

Regards,
Marcelo.

**Comment by marcelobusico** [comment]
@salemXpresso Plugin uploaded to: http://plugins.netbeans.org/plugin/50532 (you can download from there but it won't appear in plugin center for now).

**Comment by marcelobusico** [comment]
@salemXpresso If you can please rate it 😄

**Comment by salemXpresso** [comment]
Thank you very much for your reactivity, for sure I'm going to put a 5 stars to this very useful plugin 😃

**Pull request merged**
